### ISSUE TITLE
Trunk Build Error on Master branch. "Loop Helper" not found in scope.

### ISSUE THREAD

**Issue by Sigmoidle** [darthdeus/comfy#92]
OS: macOS Sonoma
CPU: M2
Comfy commit: 052307e on master branch

When using: `trunk build --release --features comfy/ci-release`

On my game: https://github.com/Sigmoidle/cat_ball_wow

I get this error: 

```
2024-02-29T19:59:48.991342Z  INFO 🚀 Starting trunk 0.18.8
2024-02-29T19:59:48.992373Z  INFO 📦 starting build
2024-02-29T19:59:48.993664Z  INFO spawning asset pipelines
2024-02-29T19:59:49.161775Z  INFO building learning_comfy
    Updating crates.io index
   Compiling comfy v0.3.1 (https://github.com/Sigmoidle/comfy_touch_support.git#91ca4001)
error[E0425]: cannot find value `loop_helper` in this scope
   --> /Users/sigmoid/.cargo/git/checkouts/comfy_touch_support-d720c83557467eae/91ca400/comfy/src/game_loop.rs:193:17
    |
193 |                 loop_helper.set_target_rate(game_config().target_framerate);
    |                 ^^^^^^^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0425`.
error: could not compile `comfy` (lib) due to 1 previous error
2024-02-29T19:59:52.736741Z ERROR ❌ error
error from build pipeline

Caused by:
    0: HTML build pipeline failed (1 errors), showing first
    1: error from asset pipeline
    2: error during cargo build execution
    3: cargo call to executable 'cargo' with args: '["build", "--target=wasm32-unknown-unknown", "--manifest-path", "/Users/sigmoid/Documents/my_code/learning_comfy/Cargo.toml", "--release", "--features", "comfy/ci-release"]' returned a bad status: exit status: 101
Error: error from build pipeline

Caused by:
    0: HTML build pipeline failed (1 errors), showing first
    1: error from asset pipeline
    2: error during cargo build execution
    3: cargo call to executable 'cargo' with args: '["build", "--target=wasm32-unknown-unknown", "--manifest-path", "/Users/sigmoid/Documents/my_code/learning_comfy/Cargo.toml", "--release", "--features", "comfy/ci-release"]' returned a bad status: exit status: 101
```

This command previously worked on Comfy version 0.3.1 from crates.io

**Comment by Sigmoidle** [comment]
Fixed by commit: fb1532c
